export const LOAD_REGIONS_LOADING = "LOAD_REGIONS_LOADING";
export const LOAD_REGIONS_SUCCESS = "LOAD_REGIONS_SUCCESS";
export const LOAD_REGIONS_ERROR = "LOAD_REGIONS_ERROR";

export const LOAD_FORECAST_LOADING = "LOAD_FORECAST_LOADING";
export const LOAD_FORECAST_SUCCESS = "LOAD_FORECAST_SUCCESS";
export const LOAD_FORECAST_ERROR = "LOAD_FORECAST_ERROR";

export const FILTER_REGION = "FILTER_REGION";
